name: BBP_RTQC 
channels:
  - conda-forge
  - defaults
dependencies:
#  - _libgcc_mutex
  - blas
  - ca-certificates
    #  - intel-openmp
  - ld_impl_linux-64
    #  - libgfortran-ng
    #  - libstdcxx-ng
  - pandoc
  - poppler-data
    #  - libgcc-ng
    #  - mkl
  - tbb
  - bzip2
  - expat
  - freexl
  - geos
  - giflib
  - icu
  - jpeg
  - json-c
  - libffi
    #  - libgcc
  - libiconv
  - libllvm9
  - libsodium
  - libuuid
  - libuv
    #  - libxkbcommon
  - lz4-c
  - ncurses
  - nspr
  - openssl
  - pcre
  - pixman
  - pthread-stubs
  - tzcode
  - xorg-kbproto
  - xorg-libice
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zlib
  - boost-cpp
  - gettext
  - hdf4
  - hdf5
  - jasper
  - libclang
  - libedit
  - libpng
  - libssh2
  - libxcb
  - libxml2
  - nodejs
  - readline
  - tk
  - xerces-c
  - xorg-libsm
  - zeromq
  - zstd
  - freetype
  - g2clib
    #  - hdfeos2
    #  - hdfeos5
  - kealib
  - krb5
  - libkml
  - libtiff
  - libxslt
  - sqlite
  - xorg-libx11
  - fontconfig
  - libcurl
  - libpq
  - libwebp
  - nss
  - openjpeg
  - proj
  - python
  - xorg-libxext
  - xorg-libxrender
  - attrs
  - backcall
  - cfitsio
  - chardet
  - click
  - cloudpickle
  - curl
  - dask-core
  - decorator
  - defusedxml
  - fsspec
  - geotiff
  - glib
  - heapdict
  - idna
  - ipython_genutils
  - kiwisolver
  - libspatialite
  - locket
  - markupsafe
  - msgpack-python
  - olefile
  - pandocfilters
  - parso
  - pickleshare
  - ply
  - postgresql
  - prometheus_client
  - psutil
  - ptyprocess
  - pycparser
  - pyparsing
  - pyproj
  - pyshp
  - pysocks
  - python_abi
  - pytz
  - pyyaml
  - send2trash
  - six
  - sortedcontainers
  - tblib
  - testpath
  - toolz
  - tornado
  - wcwidth
  - webencodings
  - zipp
  - cairo
  - certifi
  - cffi
  - cycler
  - cytoolz
  - dbus
  - entrypoints
  - future
  - gstreamer
  - importlib-metadata
  - jedi
  - lesscpy
  - libdap4
  - libnetcdf
  - lxml
  - mistune
#  - mkl-service
  - packaging
  - partd
  - pexpect
  - pillow
  - portalocker
  - pyrsistent
  - python-dateutil
  - pyzmq
  - terminado
  - tiledb
  - traitlets
  - zict
  - argon2-cffi
  - cryptography
  - distributed
  - gst-plugins-base
  - importlib_metadata
  - jupyter_core
  - numpy-base
  - poppler
  - setuptools
  - bleach
  - jinja2
  - jsonschema
  - jupyter_client
  - libgdal
  - pygments
  - pyopenssl
  - qt
  - wheel
  - nbformat
  - pip
  - prompt_toolkit
  - pyqt
  - urllib3
  - ipython
  - nbconvert
  - requests
  - ipdb
  - ipykernel
  - pyepsg
  - ipyparallel
  - notebook
  - jupyter_contrib_core
  - metakernel
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - octave_kernel
  - jupyter_contrib_nbextensions
  - scipy
  - gsw
  - matplotlib
  - matplotlib-base
  - jupyterthemes
  - pyhdf
  - pykdtree
    #  - pynio
  - shapely
  - cartopy
  - asteval
  - uncertainties
  - lmfit
  - bottleneck
  - cftime
  - netcdf4
  - nc-time-axis
    #  - mkl_fft
    #  - mkl_random
  - numpy
  - pandas
  - dask
  - pseudonetcdf
  - xarray
  - bs4
  - xlsxwriter
  - scikit-learn
  - seawater
  - rockhound
  - gulp
  - notedown
